name: Whitesource Prioritize Java with Gradle

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release* ]

jobs:
  WhiteSource-Prioritize:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
            
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: WhiteSource Prioritize Scan
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
      run: |
        cat <<EOF > eua.config
        apiKey=$WS_APIKEY
        userKey=$WS_USERKEY
        wss.url=https://saas.whitesourcesoftware.com/agent
        productName=GH_${{ github.event.repository.name }}
        projectName=${{ github.ref }}_Prioritize
        enableImpactAnalysis=true
        requireKnownSha1=false
        resolveAllDependencies=false
        gradle.resolveDependencies=true
        gradle.aggregateModules=true
        gradle.preferredEnvironment=wrapper
        gradle.wrapperPath=./gradlew
        fileSystemScan=false
        generateProjectDetailsJson=true
        EOF
        cat eua.config
        echo config created successfully
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        curl -LJO https://unified-agent.s3.amazonaws.com/xModuleAnalyzer/xModuleAnalyzer.jar
        echo Unified Agent downloaded successfully
        java -jar wss-unified-agent.jar -d $PWD -analyzeMultiModule multimodule.txt
        echo 'multimodule.txt contents'
        cat multimodule.txt
        java -jar xModuleAnalyzer.jar -xModulePath multimodule.txt -fsaJarPath ./wss-unified-agent.jar -c ./eua.config -aggregateModules true
