include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml'

renovate:
  variables:
    RENOVATE_EXTRA_FLAGS: --autodiscover=true --onboarding=true --autodiscover-filter=group1/*
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
