# add github_com_token & renovate_password as variables
image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
      - step:
          name: 'Renovate' 
          script:
            - export RENOVATE_ENDPOINT='https://api.bitbucket.org/'
            - export RENOVATE_PLATFORM='bitbucket'
            - export RENOVATE_REPOSITORIES=$BITBUCKET_REPO_FULL_NAME
            - export RENOVATE_USERNAME=$BITBUCKET_WORKSPACE
            - export RENOVATE_CONFIG='{"onboardingConfig":{"extends":["github>whitesource/merge-confidence:beta","github>samq-ghdemo/renovate:demo"]}}'
            - docker run --rm -e GITHUB_COM_TOKEN=$GITHUB_COM_TOKEN -e RENOVATE_USERNAME -e RENOVATE_PASSWORD=$RENOVATE_PASSWORD -e RENOVATE_CONFIG -e RENOVATE_ENDPOINT -e RENOVATE_PLATFORM -e RENOVATE_REPOSITORIES renovate/renovate
          services:
            - docker