trigger:
- release*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: 'build/build.csproj'

- script: |
    curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    echo Unified Agent downloaded successfully
    CSPROJ=$(basename $(find ./ -type f -wholename "*/src/*.csproj") .csproj)
    DLL=$(find ./ -type f -wholename "*/publish/*$CSPROJ.dll")
    java -jar wss-unified-agent.jar -appPath $DLL -d ./
  env:
    WS_APIKEY: $(APIKEY)
    WS_USERKEY: $(USERKEY)
    WS_PRODUCTNAME: AZDO_$(System.TeamProject)
    WS_PROJECTNAME: $(Build.Repository.Name)_$(Build.SourceBranchName)_Prioritize
    WS_ENABLEIMPACTANALYSIS: true
    WS_REQUIREKNOWNSHA1: false
    WS_RESOLVEALLDEPENDENCIES: false
    WS_NUGET_RESOLVEDEPENDENCIES: true
    WS_NUGET_RESTOREDEPENDENCIES: true
    WS_FILESYSTEMSCAN: false
    WS_EXCLUDES: '**/build/** **/tests/**'
  displayName: 'Unified Agent Prioritize Scan'
  