name: 'whitesource-ua-azdo-npm'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'NPM Install'
  inputs:
    customCommand: install --package-lock

- task: CmdLine@2
  displayName: 'WhiteSource Scan'
  enabled: true
  continueOnError: false
  env: {
    WS_APIKEY: "$(WS_ApiKey)",
    WS_WSS_URL: "$(WS_WssUrl)",
    WS_RESOLVEALLDEPENDENCIES: false,
    WS_NPM_RESOLVEDEPENDENCIES: true,
    WS_FILESYSTEMSCAN: false,
    WS_SCANCOMMENT: "AzDO $(Build.DefinitionName) - $(Build.SourceVersionMessage)"
  }
  inputs:
    script: |
      curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
      echo Unified Agent downloaded successfully
      echo WhiteSource Scan
      java -jar wss-unified-agent.jar -product "AZDO_$(Build.Repository.Name)" -project "$(Build.DefinitionName)"
    failOnStderr: false
