name: Whitesource Prioritize Java with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
    - name: WhiteSource Unified Agent Scan
      env:
        APIKEY: ${{secrets.APIKEY}}
      run: |
        cat <<EOF > eua.config
        apiKey=$APIKEY
        productName=GH_${{ github.event.repository.name }}
        projectName=${{ github.ref }}_Prioritize
        enableImpactAnalysis=true
        requireKnownSha1=false
        resolveAllDependencies=false
        maven.resolveDependencies=true
        maven.aggregateModules=true
        includes=**/*c **/*cc **/*cp **/*cpp **/*cxx **/*c++ **/*h **/*hh **/*hpp **/*hxx **/*h++ **/*m **/*mm **/*pch **/*c# **/*cs **/*csharp **/*go **/*goc **/*js **/*pl **/*plx **/*pm **/*ph **/*cgi **/*fcgi **/*pod **/*psgi **/*al **/*perl **/*t **/*pl6 **/*p6m **/*p6l **/*pm6 **/*nqp **/*6pl **/*6pm **/*p6 **/*php **/*py **/*rb **/*swift **/*java **/*clj **/*cljx **/*cljs **/*cljc **/*jar **/*egg **/*dll **/*tar.gz **/*tgz **/*zip **/*whl **/*gem **/*apk **/*air **/*dmg **/*exe **/*gem **/*gzip **/*msi **/*nupkg **/*swc **/*swf **/tar.bz2 **/pkg.tar.xz **/(u)?deb **/(a)?rpm
        EOF
        less eua.config
        echo config created successfully
        curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
        curl -o xModuleAnalyzer.jar https://unified-agent.s3.amazonaws.com/xModuleAnalyzer/xModuleAnalyzer-21.3.2.jar
        echo UA downloaded successfully
        java -jar wss-unified-agent.jar -d ./ -analyzeMultiModule multimodule.txt
        echo 'multimodule.txt contents'
        cat multimodule.txt
        java -jar xModuleAnalyzer.jar -xModulePath multimodule.txt -fsaJarPath ./wss-unified-agent.jar -c ./eua.config -aggregateModules true
