trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: curl -LJO https://downloads-sast.mend.io/sast-cli/linux/mendsastcli && chmod +x mendsastcli
  displayName: 'Downloading WS SAST Tool'

- script: ./mendsastcli --dir ./ --name=$(Build.Repository.Name)$(Build.SourceBranchName) --app AZ$(System.TeamProject)
  displayName: 'Run WS SAST'
  env:
    SAST_ORGANIZATION: $(SAST_ORGANIZATION)
    SASTCLI_TOKEN: $(SASTCLI_TOKEN)
    SAST_SERVER: https://saas.mend.io/sast/
