# All environment variables are defined per: https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/#User-defined-variables
# The required parameters are:
# SASTCLI_TOKEN
# SAST_ORGANIZATION
# SAST_SERVER

image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: 'Mend SAST Scan'
        script:
          - curl -LJO https://downloads-sast.mend.io/sast-cli/linux/mendsastcli && chmod +x mendsastcli
          - ./mendsastcli --dir $BITBUCKET_CLONE_DIR --name="$BITBUCKET_REPO_FULL_NAME-$BITBUCKET_BRANCH" --app=$BITBUCKET_REPO_FULL_NAME --baseline=true