name: SAST

on:
  push:
    branches: [ main ]

jobs:
  mend-sast:
    name: Mend-SAST
    runs-on: ubuntu-latest
    env:
      SAST_ORGANIZATION: ${{secrets.SAST_ORGANIZATION}}
      SASTCLI_TOKEN: ${{secrets.SASTCLI_TOKEN}}
      SAST_SERVER: https://saas.mend.io/sast/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Download CLI
      - name: Download CLI
        run: curl -LJO https://downloads-sast.mend.io/sast-cli/linux/mendsastcli && chmod +x mendsastcli
      # Run CLI
      - name: Run Mend-SAST
        run: ./mendsastcli --dir ./ --name=${{github.event.repository.name}}-${{github.ref_name}}-${{github.sha}} --app=${{github.event.repository.name}} --baseline=true
