# add APIKEY and USERKEY as an environment variable - https://gitlab.com/help/ci/variables/README
default:
    image: rappdw/docker-java-python

stages:
  - build
  - scan

pip_build:
  image: rappdw/docker-java-python
  stage: build
  script: "pip install -r requirements.txt"

  cache:
    key: "cache-$PIP_PKG-$CI_PIPELINE_ID"
    paths:
    - ${CI_PROJECT_DIR}/

ws_scan:
  stage: scan
  variables:
    WS_APIKEY: $API_KEY
    WS_USERKEY: $USER_KEY
    WS_WSS_URL: "https://saas.whitesourcesoftware.com/agent"
    WS_PRODUCTNAME: $CI_PROJECT_NAME
    WS_PROJECTNAME: $CI_COMMIT_REF_NAME
  script:
    - echo "Downloading Mend Unified Agent"
    - curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    - echo "Mend Scan"
    - java -jar ./wss-unified-agent.jar
